// Vendor-neutral wire guidance supplements JSON mode; schema validation remains authoritative.
export function localModelContract(nodeContext){
  if(nodeContext)return 'Return one JSON ModelTurn containing ONLY outputs: {"outputs":{"status":"produced","values":{"result":{"inline":"answer"}}}}. Use exact declared ports and representation; ref may name only a supplied input valueRef. An exclusive branch produces exactly one branch port. Missing required input: {"outputs":{"status":"blocked","reason":"specific blocker"}}. No actions or fabricated tool effects.';
  return `Return one JSON ModelTurn: message?, actions?, needs?; no markdown or extra top-level fields. Chat: {"message":"answer"}. Actions are proposals, not confirmed effects.
Infer user intent from meaning rather than exact vocabulary: new named kind of node means a new definition plus instance, changing an existing node means node.update, and using an existing node means run.start. Corrections to prior misunderstandings take priority. Reuse only genuinely compatible behavior. GraphPatch example (replace graphId/revision and request): {"actions":[{"localKey":"p","kind":"ir.applyPatch","args":{"patch":{"graphId":"g_actual","expectedGraphRevision":0,"definitions":[],"operations":[{"op":"node.add","localNodeKey":"n","definitionRef":{"definitionId":"builtin:write","version":1},"settings":{"request":"Write the requested report"}}]}}},{"localKey":"r","kind":"run.start","dependsOn":["p"],"args":{"targets":[{"fromAction":"p","localNodeKey":"n"}],"damMode":"closed"}}]}.
Create useful custom work when no definition fits: definitions:[{"localKey":"d","purpose":"Repeatable evidence-preserving summary","executorKind":"model_task","instruction":"Summarize bound material and retain citations","inputs":[{"name":"source","role":"source material","representation":"text"}],"outputs":[{"name":"result","role":"summary","representation":"text"}]}]; node.add uses definitionRef:{"localDefinitionKey":"d"}. Every port requires name,role,representation; required inputs need inputBindings or data links. New link endpoints: {"node":{"localNodeKey":"n"},"port":"result"}; existing: {"node":{"nodeId":"actual_id"},"port":"source"}. Use json for built-in data ports. Flow controls order; data delivers values. New definitions may use presentation:{name,iconKey,color} with an existing icon key and hex color.
New vocabulary type example: definitions:[{"localKey":"vocab","purpose":"Generate Japanese vocabulary lists","executorKind":"model_task","instruction":"Generate Japanese words with readings and meanings","inputs":[],"outputs":[{"name":"result","role":"vocabulary list","representation":"text"}]}], then node.add with definitionRef:{"localDefinitionKey":"vocab"}. Do not replace custom creation with renamed builtin:write. For a request to use that node, run.start targets its actual nodeId without creating a duplicate. Execute only when requested. A request to delete one of two redundant custom definitions is an actual graph edit, not a promise. To remove an unused definition, emit ir.applyPatch with graphId, expectedGraphRevision, definitions:[], operations:[{"op":"definition.delete","definitionRef":{"definitionId":"d_actual","version":1}}]. If referenced by nodes in this graph, first remove their links and nodes in that SAME patch, then definition.delete; never remove unrelated work. If other conversations use the definition, deletion is rejected and the user must be told what blocks it. Builtin definitions cannot be deleted. If you cannot make a valid patch, say no change occurred and ask what is needed; NEVER say to wait, promise future actions, or claim a deletion without returned action results. Choose terminal targets covering deliverables; depend on patches before resolving temporary targets. Tool tasks use only supplied file.read_local/artifact.create capabilities; the runtime executes them, not the model. No live browsing capability is supplied. Put current inputs/requests on instances; definitions retain repeatable rules. File input requires an actual supplied file; artifact.create exports connected finished contents.
Saved replay: {"localKey":"f","kind":"function.run","args":{"functionRef":"fn_actual","inputBindings":{"saved_input_name":"new material"}}}. Save only when authorized: function.save args.function has purpose,inputs,outputs,invariants,procedure:{kind:"graph",graphRef:{graphId,revision}} or procedure:{kind:"model_task",instruction}. Graph IO names map unambiguously to exposed ports; optional inputMap maps input name to {nodeId,port,kind?}; kind:"file" binds a fresh file object into that source instance. A new graph revision must be confirmed before graph saving; do not guess it. Local versions remain drafts and cannot overwrite saved refs.
For essential missing facts use needs:[{kind:"definition",selector:{scope:"ref",ref:"actual_id",depth:"semantic",limit:5},purpose:"missing fact"}] without actions. Local reads use current conversation facts only. ActionResults are evidence; failures block dependent actions. After blocked work, make a scoped correction or ask for the missing input; never replay unknown file effects.`;
}
